# Generated by Django 5.2.9 on 2026-01-26 18:26

import billing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=50, verbose_name='Nachname')),
                ('firstName', models.CharField(max_length=50, verbose_name='Vorname')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=100, verbose_name='Leistung')),
                ('preis', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Preis (€)')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('abrechnungs_nr', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Abrechnungs Nummer')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnose', models.CharField(max_length=200, verbose_name='Diagnose')),
                ('behandlung', models.TextField(blank=True, verbose_name='Behandlung')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungsdatum')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='billing.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnungsNummer', models.CharField(default=billing.models.generateInvoiceNumber, editable=False, max_length=20, unique=True)),
                ('zahlungsDatum', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('SENT', 'Gesendet'), ('PAID', 'Bezahlt')], default='DRAFT', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.patient', verbose_name='Rechnungs-Patient')),
                ('services', models.ManyToManyField(to='billing.service')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='billing.bill')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Leistung', to='billing.service')),
            ],
        ),
    ]
