# Generated by Django 6.0 on 2025-12-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lastName", models.CharField(max_length=50, verbose_name="Nachname")),
                ("firstName", models.CharField(max_length=50, verbose_name="Vorname")),
                ("adress", models.TextField(verbose_name="Adresse")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Adresse"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serviceName",
                    models.CharField(max_length=100, verbose_name="Leistung"),
                ),
                ("price", models.IntegerField(max_length=6, verbose_name="Preis (€)")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
            ],
        ),
    ]
