# Generated by Django 5.2.10 on 2026-01-26 21:31

import billing.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price (€)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('billing_code', models.CharField(max_length=10, verbose_name='Billing Code')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=200, verbose_name='Diagnosis')),
                ('treatment', models.TextField(blank=True, verbose_name='Treatment')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='billing.patient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=billing.models.generate_invoice_number, editable=False, max_length=20, unique=True, verbose_name='Invoice Number')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('due_date', models.DateField(default=django.utils.timezone.now, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='billing.patient', verbose_name='Patient')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='billing.service')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='services',
            field=models.ManyToManyField(related_name='bills', through='billing.InvoiceItem', to='billing.service', verbose_name='Services'),
        ),
    ]
