# Generated by Django 6.0 on 2025-12-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Preis (€)"),
        ),
    ]
