# Generated by Django 6.0 on 2025-12-14 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_alter_service_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="adress",
            new_name="address",
        ),
    ]
