# Generated by Django 6.0 on 2025-12-16 19:29

import billing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_rename_adress_patient_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="description",
            new_name="beschreibung",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="price",
            new_name="preis",
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rechnungsNummer",
                    models.CharField(
                        default=billing.models.generateInvoiceNumber,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("zahlungsDatum", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Entwurf"),
                            ("SENT", "Gesendet"),
                            ("PAID", "Bezahlt"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.patient",
                        verbose_name="Rechnungs-Patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preis",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preis"
                    ),
                ),
                (
                    "rechnung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Items",
                        to="billing.bill",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Leistung",
                        to="billing.service",
                    ),
                ),
            ],
        ),
    ]
