# Generated by Django 6.0 on 2025-12-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_rename_description_service_beschreibung_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="services",
            field=models.ManyToManyField(to="billing.service"),
        ),
        migrations.AlterField(
            model_name="service",
            name="preis",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="Preis (€)"
            ),
        ),
    ]
