# Generated by Django 5.2.9 on 2025-12-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='abrechnungs_nr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Abrechnungs Nummer'),
            preserve_default=False,
        ),
    ]
